const services = [
  {
    id: "supabase",
    name: "Supabase",
    monogram: "S",
    color: "#3ecf8e",
    endpoint: "https://mcp.supabase.com/mcp",
    authModes: ["oauth", "pat"],
    maturity: "official",
    description: "Projects, databases, functions, and development tooling.",
    scopeLabel: "Project ref",
    supportsReadOnly: true,
  },
  {
    id: "github",
    name: "GitHub",
    monogram: "GH",
    color: "#a8b3cf",
    endpoint: "https://api.githubcopilot.com/mcp/",
    authModes: ["pat", "oauth"],
    maturity: "official",
    description: "Repositories, pull requests, issues, and workflows.",
    scopeLabel: "Organization or account",
  },
  {
    id: "vercel",
    name: "Vercel",
    monogram: "V",
    color: "#ffffff",
    endpoint: "https://mcp.vercel.com",
    authModes: ["oauth"],
    maturity: "restricted",
    description: "Projects, deployments, logs, and documentation.",
    scopeLabel: "Team or account",
  },
  {
    id: "higgsfield",
    name: "Higgsfield",
    monogram: "H",
    color: "#ff75dd",
    endpoint: "",
    authModes: ["apiKey"],
    maturity: "adapter",
    description: "Experimental custom endpoint for image and video workflows.",
    scopeLabel: "Workspace",
  },
  {
    id: "framer",
    name: "Framer",
    monogram: "F",
    color: "#7c5cff",
    endpoint: "",
    authModes: ["apiKey"],
    maturity: "adapter",
    description: "Experimental custom endpoint for project-bound Server API adapters.",
    scopeLabel: "Project URL or ID",
  },
  {
    id: "linear",
    name: "Linear",
    monogram: "L",
    color: "#8a8cff",
    endpoint: "https://mcp.linear.app/mcp",
    authModes: ["oauth", "apiKey"],
    maturity: "official",
    description: "Issues, projects, comments, and workspace planning.",
    scopeLabel: "Workspace",
    supportsReadOnly: true,
  },
  {
    id: "sentry",
    name: "Sentry",
    monogram: "SE",
    color: "#c8a6ff",
    endpoint: "https://mcp.sentry.dev/mcp",
    authModes: ["oauth"],
    maturity: "official",
    description: "Errors, performance, issues, and project diagnostics.",
    scopeLabel: "Organization/project path",
  },
  {
    id: "stripe",
    name: "Stripe",
    monogram: "ST",
    color: "#635bff",
    endpoint: "https://mcp.stripe.com",
    authModes: ["oauth", "apiKey"],
    maturity: "official",
    description: "Payments, customers, subscriptions, and documentation.",
    scopeLabel: "Account",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    monogram: "CF",
    color: "#f6821f",
    endpoint: "https://mcp.cloudflare.com/mcp",
    authModes: ["oauth", "apiToken"],
    maturity: "official",
    description: "Workers, infrastructure, security, and account analytics.",
    scopeLabel: "Account",
  },
  {
    id: "atlassian",
    name: "Atlassian",
    monogram: "A",
    color: "#579dff",
    endpoint: "https://mcp.atlassian.com/v1/mcp",
    authModes: ["oauth", "apiToken"],
    maturity: "official",
    description: "Jira, Confluence, and connected team knowledge.",
    scopeLabel: "Site",
  },
  {
    id: "custom",
    name: "Custom MCP",
    monogram: "+",
    color: "#6f7c9b",
    endpoint: "",
    authModes: ["oauth", "bearer", "apiKey"],
    maturity: "custom",
    description: "Any Streamable HTTP MCP endpoint.",
    scopeLabel: "Optional scope label",
  },
];

const serviceById = Object.fromEntries(services.map((service) => [service.id, service]));

module.exports = { services, serviceById };
