const services = [
  {
    id: "supabase",
    name: "Supabase",
    monogram: "S",
    color: "#3ecf8e",
    endpoint: "https://mcp.supabase.com/mcp",
    authModes: ["oauth", "pat"],
    maturity: "official",
    description: "Projects, databases, functions, and development tooling.",
    scopeLabel: "Project ref",
    supportsReadOnly: true,
  },
  {
    id: "github",
    name: "GitHub",
    monogram: "GH",
    color: "#a8b3cf",
    endpoint: "https://api.githubcopilot.com/mcp/",
    authModes: ["pat", "oauth"],
    maturity: "official",
    description: "Repositories, pull requests, issues, and workflows.",
    scopeLabel: "Organization or account",
  },
  {
    id: "vercel",
    name: "Vercel",
    monogram: "V",
    color: "#ffffff",
    endpoint: "https://mcp.vercel.com",
    authModes: ["oauth"],
    maturity: "restricted",
    description: "Projects, deployments, logs, and documentation.",
    scopeLabel: "Team or account",
  },
  {
    id: "higgsfield",
    name: "Higgsfield",
    monogram: "H",
    color: "#ff75dd",
    endpoint: "https://mcp.higgsfield.ai/mcp",
    authModes: ["oauth"],
    maturity: "official",
    description: "Official MCP for images, video, characters, audio, and account credits.",
    scopeLabel: "Higgsfield account",
    endpointLocked: true,
  },
  {
    id: "posthog",
    name: "PostHog",
    monogram: "PH",
    color: "#f54e00",
    endpoint: "https://mcp.posthog.com/mcp",
    authModes: ["oauth"],
    maturity: "official",
    description: "Analytics, feature flags, experiments, errors, and product data.",
    scopeLabel: "Organization or project",
    endpointLocked: true,
  },
  {
    id: "neon",
    name: "Neon",
    monogram: "N",
    color: "#b9ff80",
    endpoint: "https://mcp.neon.tech/mcp",
    authModes: ["oauth"],
    maturity: "official",
    description: "Postgres projects, branches, databases, and SQL workflows.",
    scopeLabel: "Project or organization",
    endpointLocked: true,
    supportsReadOnly: true,
  },
  {
    id: "notion",
    name: "Notion",
    monogram: "N",
    color: "#ffffff",
    endpoint: "https://mcp.notion.com/mcp",
    authModes: ["oauth"],
    maturity: "official",
    description: "Pages, databases, workspace search, and connected knowledge.",
    scopeLabel: "Workspace",
    endpointLocked: true,
  },
  {
    id: "hubspot",
    name: "HubSpot",
    monogram: "HS",
    color: "#ff7a59",
    endpoint: "https://mcp.hubspot.com",
    authModes: ["oauth"],
    maturity: "official",
    description: "CRM records, contacts, companies, deals, and customer context.",
    scopeLabel: "HubSpot account",
    endpointLocked: true,
    requiresOAuthClient: true,
    oauthCallbackPort: 7260,
    oauthSetupUrl: "https://developers.hubspot.com/docs/apps/developer-platform/build-apps/integrate-with-the-remote-hubspot-mcp-server",
  },
  {
    id: "slack",
    name: "Slack",
    monogram: "S",
    color: "#ffffff",
    endpoint: "https://mcp.slack.com/mcp",
    authModes: ["oauth"],
    maturity: "official",
    description: "Workspace search, channels, messages, files, and approved actions.",
    scopeLabel: "Slack workspace",
    endpointLocked: true,
    requiresOAuthClient: true,
    oauthCallbackPort: 48125,
    oauthSetupUrl: "https://docs.slack.dev/ai/slack-mcp-server",
  },
  {
    id: "shopify",
    name: "Shopify",
    monogram: "S",
    color: "#95bf47",
    endpoint: "",
    authModes: ["oauth"],
    maturity: "restricted",
    description: "Guided UCP storefront integration for catalog, cart, checkout, and orders.",
    scopeLabel: "Store domain",
    requiresUcpProfile: true,
    oauthSetupUrl: "https://shopify.dev/docs/agents/get-started/quickstart",
  },
  {
    id: "framer",
    name: "Framer",
    monogram: "F",
    color: "#7c5cff",
    endpoint: "",
    authModes: ["apiKey"],
    maturity: "adapter",
    description: "Experimental custom endpoint for project-bound Server API adapters.",
    scopeLabel: "Project URL or ID",
  },
  {
    id: "linear",
    name: "Linear",
    monogram: "L",
    color: "#8a8cff",
    endpoint: "https://mcp.linear.app/mcp",
    authModes: ["oauth", "apiKey"],
    maturity: "official",
    description: "Issues, projects, comments, and workspace planning.",
    scopeLabel: "Workspace",
    supportsReadOnly: true,
  },
  {
    id: "sentry",
    name: "Sentry",
    monogram: "SE",
    color: "#c8a6ff",
    endpoint: "https://mcp.sentry.dev/mcp",
    authModes: ["oauth"],
    maturity: "official",
    description: "Errors, performance, issues, and project diagnostics.",
    scopeLabel: "Organization/project path",
  },
  {
    id: "stripe",
    name: "Stripe",
    monogram: "ST",
    color: "#635bff",
    endpoint: "https://mcp.stripe.com",
    authModes: ["oauth", "apiKey"],
    maturity: "official",
    description: "Payments, customers, subscriptions, and documentation.",
    scopeLabel: "Account",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    monogram: "CF",
    color: "#f6821f",
    endpoint: "https://mcp.cloudflare.com/mcp",
    authModes: ["oauth", "apiToken"],
    maturity: "official",
    description: "Workers, infrastructure, security, and account analytics.",
    scopeLabel: "Account",
  },
  {
    id: "atlassian",
    name: "Atlassian",
    monogram: "A",
    color: "#579dff",
    endpoint: "https://mcp.atlassian.com/v1/mcp",
    authModes: ["oauth", "apiToken"],
    maturity: "official",
    description: "Jira, Confluence, and connected team knowledge.",
    scopeLabel: "Site",
  },
  {
    id: "custom",
    name: "Custom MCP",
    monogram: "+",
    color: "#6f7c9b",
    endpoint: "",
    authModes: ["oauth", "bearer", "apiKey"],
    maturity: "custom",
    description: "Any Streamable HTTP MCP endpoint.",
    scopeLabel: "Optional scope label",
  },
];

const serviceById = Object.fromEntries(services.map((service) => [service.id, service]));

module.exports = { services, serviceById };
